### ISSUE TITLE
大神，训练代码修改哪些

### ISSUE THREAD

**Issue by maimaiya** [JunnYu/Paddle-AI-Writer#1]
大神，如果在aistudio上运行，需要把原来的训练代码改成paddle的，自己尝试按照api映射表改了些函数，无法运行，有报错：  import imp
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from src.model import GPT, GPTConfig
  File "/home/aistudio/train/RWKV-LM-2.00/src/model.py", line 60, in <module>
    class RWKV_TimeMix(nn.layer):
TypeError: module() takes at most 2 arguments (3 given)
请问大神你的训练代码修改了哪些？

**Comment by JunnYu** [comment]
我写的代码应该没问题，你自己修改的代码可能存在部分问题class RWKV_TimeMix(nn.layer)这个layer就感觉不对劲怎么小写了

**Comment by cheng539539** [comment]
直接用RWKV-LM训练成pth，让后用这个项目里面的/paddle_src/convert_pytorch2paddle.py转成.pdparams不就行了。何必纠结。
